### PR TITLE
added Alberto as maintainer

### PR DESCRIPTION
**Pull request by zerothi**

### CODE REVIEW

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by zerothi** [comment]
@conda-forge-admin, please update team

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
This feedstock was created 2 days ago, there is nothing to re-render.

**Comment by zerothi** [comment]
@ocefpaf I just don't get why the staged recipe build on Unix, while now it doesn't. When it got accepted it build on Unix without problems. Hence, I tried to rerender the PR because I wanted it to accept the Unix build. 

Again, I haven't changed anything but the team, before it got merged it build on unix, now the unix-build is disabled?

**Comment by jakirkham** [comment]
Please drop the `py36` part from the `skip` and re-render. Selecting `python` version makes no sense here as this doesn’t depend on `python`. Expect that is causing the issue.

**Comment by jakirkham** [comment]
Are we sure it was actually building at `staged-recipes`?

**Comment by zerothi** [comment]
Yes:
https://circleci.com/gh/conda-forge/staged-recipes/23654?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

See PR here: https://github.com/conda-forge/staged-recipes/pull/5026 the CI builds all the binaries for Unix and correctly says that for Mac and Win it is disabled.

**Comment by jakirkham** [comment]
Ok, I think that has to do with the fact that `conda-build-all` effectively [forces a Python matrix]( https://github.com/conda-forge/staged-recipes/blob/master/.circleci/run_docker_build.sh#L67 ). So even though your recipe does not depend on `python`, that `skip` would still be meaningful in that context.

**Pull request merged**
