### PR TITLE
Main v5.0

### PR DESCRIPTION
**Pull request by zerothi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@zerothi Does it make sense to have a separate branch for release candidates?

**Comment by zerothi** [comment]
> @zerothi Does it make sense to have a separate branch for release candidates?

For now I will just keep `main` being the rc, once 5.0.0 is out, I don't think we'll maintain the `rc`'s. Let's see. Lets keep it simple :)

**Comment by pfebrer** [comment]
@zerothi Is there some reason why you disabled flook here?

**Comment by zerothi** [comment]
I can't exactly recall, perhaps I had a build problem in my early tries, and forgot to re-enable it, if you'd like, you can make a PR which tries to enable it? :)

**Comment by pfebrer** [comment]
Ok, I will try :+1:

I just compiled siesta in a conda environment with flook and there were some problems with `readline`, but in the end I could solve them. Let's see if the same problem arises here.

**Comment by zerothi** [comment]
Yes, this rings a bell. Something I think was solved in Siesta *after* rc1, so I think when rc2, or 5 hits the shelf, then it should be ok.

If anything, you can do a small patch to fix the build problem, that would be ok here.

**Pull request merged**
