### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by haoasakura12**
Including other postprocessing (analyses) tools absent in the previous version. Mainly optical and structural tools

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by haoasakura12** [comment]
Dear, 
I made some changes to the build.sh file adding some "cd FOLDER" and mkcp to the folders/files I need to use and are absent in the current version. According to the automatic processing, it was not correct... Could someone help me? 

I just want to include the tolls fmpdos, xv2xsf, eig2bxsf, md2axsf, rho2xsf, and vib2xsf (in folder Util/Contrib/APostnikov); hs2hsx, and hsx2hs (in folder Util/HSX); optical, and optical_input (in folder Util/Optica); and ts2ts (folder Util/ts2ts - part of Transiesta code); cdf2xsf, and cdf2grid (folder Uil/Grid); and wfsnc2fsx

**Comment by zerothi** [comment]
These are now added in the 4.1 branch, so installing siesta 4.1 should give you the required executables, let us know if you experience any problems! :)

**Comment by haoasakura12** [comment]
Dear, than you for your help. 

I installed it and found most of the requested packages. However, I couldn't find there ones in the bin folder
fmpdos, xv2xsf, eig2bxsf, md2axsf, rho2xsf, and vib2xsf (in folder Util/Contrib/APostnikov).

Could these be added to?

**Comment by zerothi** [comment]
These are now added.

**Comment by haoasakura12** [comment]
Thank you

**Comment by haoasakura12** [comment]
Dear, 

Is it possible to install the same packages in 5.0.1 version?
(I just want to include the tolls fmpdos, xv2xsf, eig2bxsf, md2axsf, rho2xsf, and vib2xsf (in folder Util/Contrib/APostnikov); hs2hsx, and hsx2hs (in folder Util/HSX); optical, and optical_input (in folder Util/Optica); and ts2ts (folder Util/ts2ts - part of Transiesta code); cdf2xsf, and cdf2grid (folder Uil/Grid); and wfsnc2fsx). 

Another question. Is D3 Grimme's correction avaliable in 5.0.1?

Thank you for your help. If it's necessary, I could create another issue

**Comment by zerothi** [comment]
> Dear,
> 
> Is it possible to install the same packages in 5.0.1 version? (I just want to include the tolls fmpdos, xv2xsf, eig2bxsf, md2axsf, rho2xsf, and vib2xsf (in folder Util/Contrib/APostnikov); hs2hsx, and hsx2hs (in folder Util/HSX); optical, and optical_input (in folder Util/Optica); and ts2ts (folder Util/ts2ts - part of Transiesta code); cdf2xsf, and cdf2grid (folder Uil/Grid); and wfsnc2fsx).
> 
> Another question. Is D3 Grimme's correction avaliable in 5.0.1?
> 
> Thank you for your help. If it's necessary, I could create another issue

They are already there? Did you check?
if you still have problems, please open a new issues, detailing exactly what you did, and which programs are not available.

**Pull request closed without merging**
