### PR TITLE
trying to remove null from version-info

### PR DESCRIPTION
**Pull request by zerothi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Comment by pfebrer** [comment]
> It seems to have ignored the files here:

Ah no, because the compiler flags are probably inside the `siesta` binary (?)

**Comment by zerothi** [comment]
Still not fixed.
The problem is that we want to make `siesta` relocatable, but we only want the `rpath`/`path` to be updated, not the string that originates from `version-info`.

This issue is somewhat related to: https://github.com/conda/conda-build/issues/40

I think the only way to fix this is to:

1. Add CMake detection of whether we are building in conda
2. do a replacement of `PREFIX` and `BUILD_PREFIX` in flags to something less obvious, probably `<prefix>` and `<build-prefix>`

**Comment by pfebrer** [comment]
Ok, so for now the only possible fix is to patch "version-info" to not incorporate compiler flags, no?

**Pull request merged**
