### PR TITLE
enh: added phtrans to the binaries

### PR DESCRIPTION
**Pull request by zerothi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Added phtrans binary

### CODE REVIEW

**Comment by zerothi** [comment]
@conda-forge-admin, please rerender

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
By the way, can we set `4.1.5` as the default? or is 4.0.2 still the preferred stable release? I am currently a bit confused with all the max release.

**Comment by zerothi** [comment]
> By the way, can we set `4.1.5` as the default? or is 4.0.2 still the preferred stable release? I am currently a bit confused with all the max release.

I don't think it matters too much. I think we should just leave it as is for now. Once 4.2/5 will be out, 4.0 will be left alone and we can easily change the default branch.

We'll wait until that happens.

**Comment by jan-janssen** [comment]
> Also, as far as I understand `conda` does not select packages based on which is the default branch of the feedstock, rather it is from the version number and build-number. In this case 4.1.5 would be installed.

That is correct, still the conda bots only update the master channel. So as anyway 4.1.5 is installed by default I would merge it with the master branch and just maintain the latest version.

**Comment by zerothi** [comment]
Yes, but the goal is to consistently maintain two versions of siesta. So it shouldn't be merged.

I guess conda-bots can be asked in PR's to update specific branches.

**Pull request merged**
