### PR TITLE
WIP debug

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by zerothi** [comment]
As you can see the errors keeps happening for *more* and *more* files. I suspect all write statements with formats will in one way or the other create problems. 

The only thing I can see is that this build uses a mixed GCC and Gfortran version which could potentially be erroneous. But I am still very unsure where this comes from...

**Comment by beckermr** [comment]
Indeed. Something is weird but I’m sure we’ll find it!

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
I might be giving up here.

**Comment by beckermr** [comment]
and I am giving up - sorry :(

**Comment by zerothi** [comment]
@beckermr thanks for trying! :)

I will have to return to this...

**Pull request closed without merging**
